version: "3.9"

services:
  app:
    container_name: megano
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      CELERY_BROKER_URL: "redis://web_redis:6379/0"
    restart: always
    networks:
      - web_app
    ports:
      - "${APP_PORT}:8000"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
#    volumes:
#      - .:/megano

  web_redis:
    restart: always
    container_name: main_redis
    image: redis:7.2.1
    entrypoint:
      sh -c "redis-server"
    networks:
      - web_app
    ports:
      - "${REDIS_PORT}:6379"

  flower:
    restart: always
    image: mher/flower:2.0.1
    container_name: flower
    environment:
      CELERY_BROKER_URL: "redis://web_redis:6379"
      FLOWER_PORT: 5555
      FLOWER_BASIC_AUTH: "flower:flower"
    networks:
      - web_app
    ports:
      - "${FLOWER_PORT}:5555"

  db:
    image: postgres:16.0
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - web_app
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  payment_service:
    container_name: payment_app
    build:
      dockerfile: payment_service/Dockerfile
    command:
      - python
      - fake_payment.py
    ports:
      - "${PAYMENT_APP_PORT}:5000"
    networks:
      - web_app

networks:
  web_app:
    name: web_app
    driver: bridge